= Citizenfour
:hp-tags: Senior Seminar, Citizenfour, Edward Snowden

Citizenfour was an interesting documentary. By the time we watched it in my Senior Seminar class, it was a while after the whole episode, so in some sense it was like beating a dead horse. The documentary details the life of Edward Snowden directly before and during the upheaval he caused by the public release of sensitive NSA information proving that the government spied on US citizens. 

I felt like the documentary presented some good facts about the situation, and gave insight where those who did not elect to do their own research were concerned. Unfortunately, probably to make it interesting to the average viewer, the documentary seemed more focused on Snowden and his life as opposed to what Snowden _did_. This was an important distinction to me, and leant the documentary a bit of a cheezy air.

I believe Snowden made the right choice in releasing the sensitive information he had. I think in an age where we don't have any way to know what the government is doing, he brought a breath of fresh air to the public. Then again, I have ever been a proponent of small government.