= Larry Brigdes on Cyber Security
:hp-tags: Senior Seminar, Cyber Security, Larry Bridges, Hanes

Larry Bridges worked for Hanes textiles for many years, topping out as chief of cyber security before retiring. Bridges had many interesting insights to share with our Senior Seminar class about cyber security, and why it is necessary and what its impacts are for different branches of the Computer Science world. 

The most interesting part of the lecture was in mr. Bridges discussion of security problems he has had to handle in his life. He discussed his most recent large problem, directly before his retirement(naturally). This involved a hacker who was able to make a database of client information by exploiting a page routing security issue. From what he said, basically the customer information number, used at the end of the url, was just sorted in ascending order. This meant that the hacker just had to change the last number, incrementing by 1, to get to a new customer information page. Bridges said that upon recieving blackmail attempts from the hacker, the company decided to go public with the problem, informing all their customers. He further commented that none of them seemed to care much, and they did not see a drop in business over it. After the discovery, Hanes brought in the Verizon data security experts, who tracked down the hacker and dealt with it accordingly. It was a very interesting thing to learn. 

I think what I liked the most about the lecture was that we got a piece of real world experience. For all that we know our professors are some of the best and brightest, most have been involved in academia for a number of years, if not their entire career, and cannot paint an accurate picture of how an actual programming job works these days. It was almost alluring to get a taste of real world programming in the talk by Bridges, and while I can't speak for everyone else, I know it made me really excited to get out into that world. 