= Erika Forte on Career Development
:hp-tags: Senior Seminar, Careers

In our Senior Seminar class Erika Forte, an Appalachian State future careers advisor, gave a presentation about what students can do to maximize their potential to get hired. Here's what she said:

Visit the resume clinic:: 
Appalachian State offers a resume clinic to help with any questions you may have in regards to your resume. This is an invaluable tool, on the off chance that your Junior Seminar, Senior Seminar, and major advisor have not poured through your resume and cover letter already, gutting it in different ways and remolding the pieces that survived the purge.
* While this seems like a good thing, I felt a little skeptical because everyone seems to have different ideas about what a resume should look like and entail, and I have no idea how to know which higher power is correct.
Career fair:: 
Appalachian State holds 1-3 career fairs each semester. These are amazing, because it brings prospective jobs right to our front door. It cant get much easier than standing in a room with people who are trying to find someone like you.
Practice, practice:: 
Get a professor, friend, or other authority of your field to test you and give a mock interview. You would be surprised what you may learn, and more surprised to learn the things you should, but DONT, know. Appalachian State offers an interesting series of generalized mock interviews, which can be signed up for in their Career Development center.
Career Gear::
An online classifieds, in typical cork board style, for jobs. Search by multiple criteria, including year, field, job/internship, pay level, and much more. Go look at it as soon as the opportunity arises.

Basically, the thing to take away from the presentation by Erika Forte is that if you cant figure out how to find a job with all the resources Appalachian State offers, get our of our college.