= Reflections on Ethics
:hp-tags: Senior Seminar, Ethics

In my Senior Seminar class, we had an interesting discussion in regards to ethics.  This post attempts to summarize that discussion, and hit on a few points on my personal code of ethics.

* *The golden rule*
** this was mentioned by almost everyone in the class. Treat others as you would like to be treated. I agree strongly with this one, but it was kindof a copout answer in my mind.
* *Don't hurt others*
** seems simple. In everything you do, take a moment to think through possible ramifications of your actions. Will this hurt someone physically, mentally, and emotionally?
* *leave well enough alone*
** what does it really matter if someone does something you don't agree with? If the previous stated rules are being followed, it falls under the purviews of life, liberty, and the pursuit of happiness. All men are free in our nation, and if they act in good ethics as outlined above, whether or not you agree with it should have very little impact on whether or not it is _good_.