= Randy Pausch on How to Achieve your Childhood Dreams - too good to be true?
:hp-tags: Senior Seminar, Randy Pausch

"Achieving Your Childhood Dreams", the last lecture given by noted professor of computer science at Carnegie Mellon University Randy Pausch, drove its thoughts and emotions home with the precision usually reserved for surgeons, warhead launches, and masters of the game of Go. One cannot fail to be inspired by a man who knows he is going to die, and laughs directly in the facial area of this sobering truth. Pausch gave his last lecture to friends, colleagues, students, and all who wanted to attend on September 18, 2007, after discovering he had pancreatic cancer, and an expiration date of 3-6 months.

During the speech, the theme was anything goes. Pausch wheeled in giant teddy bears almost as large as himself, did pushups onstage, gave life advice, talked about himself as a boy and a man, and weaved jokes in between it all with a skill that would make any seamstress envious. The central cannon of the lecture consisted of Pausch's list of dreams, through the explanation of which he hoped to convince people to always follow their childhood dreams. Pausch's dreams are as follows:

* being in zero gravity
* playing in the NFL
* getting an article into the World Book Encyclopedia
* being Captain Kirk
* winning very large stuffed animals
* working as a Disney Imagineer

If you wanted a summary of these dreams, your looking in the wrong place. My goal here is to convince you that the lecture is worth watching, and not as a homage to a deceased mind of the computer science world, but as a game-changing outlook that might just make you evaluate your goals and reach for the lofty skyscrapers of your _dreams_.

